version: "3.9"

services:

  qstream-apis:

    build: .

    container_name: qstream-api

    env_file:
      - ../.env

    restart: unless-stopped

    expose:
      - "8082"

    networks:
      - qstream-network 

  nginx:

    image: nginx:latest

    container_name: nginx

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - qstream-apis
      
    networks:
      - qstream-network

networks:
  - qstream-network    