# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DEPLOY QSTREAM_API TO EC2 INSTANCES

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.0

        with:
          
          host: ${{ secrets.EC2_HOST }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ${{ secrets.APP_PATH }}

            git pull origin main

            cd ${{secrets.DOCKER_COMPOSE_PATH}}

            docker compose \
            -f /home/ubuntu/QSTREAM_BACKEND/backend/docker-compose.yml \
            up -d --build
